### ISSUE TITLE
"brain_regions" displayed 

### ISSUE THREAD

**Issue by maxlklaxl** [strawlab/neuron-catalog#32]
displayed in box: "Brain Regions" -> "edit" 
"Neuron Types" - > Neuron -> "Brain Regions" -> "edit" 

is redundant with the title of the box and has an "_"

**Comment by astraw** [comment]
Can you describe this better, maybe uploading an image with the problem circled? I don't understand the issue.

In a brain region view (at `/brain_regions/:_id/:name`), the list of neuron types is derived from the NeuronTypes collection. This is the filter for inclusion on the `/brain_regions/:_id/:name` page.

But what is displayed is more than just reflecting the inclusion filter: each neuron type may indeed have different expression types in different brain regions, and these are all show.

I don't see the "_" anywhere.

**Comment by maxlklaxl** [comment]
its just that line that looks to me as it would be an remnant
![screenshot_brain_regions](https://cloud.githubusercontent.com/assets/2061823/6541881/87765af6-c4e7-11e4-9567-c67f36dc77ec.jpg)
