### ISSUE TITLE
why multiselect in "Edit brain regions for neuron type" but not shown in overview?

### ISSUE THREAD

**Issue by maxlklaxl** [strawlab/neuron-catalog#33]
When it is possible to select all 3 categories "unspecific/output regions (presynaptic)/input regions (postsynaptic)" all selections should be shown in the overview (bounding box "Brain Regions"), currently only one is shown

**Comment by astraw** [comment]
Not sure what you're saying here.

Are you reporting a bug?

In the Neuron Type overview table at `/neuron_types`, the input/output/unspecified columns are shown. In the Neuron Type detail view at `/neuron_types/:_id/:name`, the "Brain Regions" panel shows expression type per row (input/output/unspecified). In the "Edit brain regions for neuron type" dialog that pops up, you can see and modify the input/output/unspecified setting per brain region.

I just checked by creating a new neuron type, selecting all three expression types in a given brain region and then seeing in the "Brain Regions" panel for that neuron type that these three expression types are shown. It works for me.

**Comment by maxlklaxl** [comment]
Oh I oversaw the other categories.
would be nice to have a color schema that separates those categories (input/output/unspecified) better. similar to the tags
